### ISSUE TITLE
The price mentioned in the Cart while store is closed is not showing up in the Product details screen. 

### ISSUE THREAD

**Issue by RoyGopotu** [AlsoltechSol/gopotu#44]
Use the following steps to generate the issue:-
Step 1:-Add a product into the cart by using guest login of the user app.
Step 2:-Mark a store as closed from the Admin portal.
Step 3:-Go to the product details screen of the same product by using guest login. At the bottom of the screen, the cart quantity and total price is getting displayed.
Step 4:- Login with an User account and go to the same product details.

Issue:- Cart value is showing up when the store is closed and user is in guest login but the cart value is not showing up when the user logged in with an user account.

![Screenshot_2023-07-03-02-27-39-20_be3ccb1b645260da397ac46f6b439743](https://github.com/AlsoltechSol/gopotu/assets/138399076/6debb88e-bde7-42a1-976b-84fddd945644)
![Screenshot_2023-07-03-02-24-14-74_be3ccb1b645260da397ac46f6b439743](https://github.com/AlsoltechSol/gopotu/assets/138399076/2bbc003f-cdee-49f0-81fc-262553d42114)

**Comment by surajlifeean** [comment]
@Megha-Sadhukhan check if this issue is only with guest login

**Comment by surajlifeean** [comment]
this only happens for guest login
