### ISSUE TITLE
User app is not opening up after the status of the mentioned products are turned on.

### ISSUE THREAD

**Issue by RoyGopotu** [AlsoltechSol/gopotu#60]
Use the following steps to generate the issue:-
Step 1:- Create a category and upload the given image.
Step 2:-Turn the Master Status, Verification status and Top Offer status On.
Step 3:- Upload the same image to the product as well.

Observation:- When a large image is uploaded as a product image, the app is not opening up.

Image to be Uploaded:-
![photo-1571091718767-18b5b1457add](https://github.com/AlsoltechSol/gopotu/assets/138399076/57a8dda8-b9f8-4724-8aa0-68bfe5d2bf19)

Issues:-
https://drive.google.com/file/d/1sunncKk-tufhDCjw_0k4LLDV6apo5Fnb/view?usp=sharing

**Comment by surajlifeean** [comment]
don't know about the issue but the burger is too yummy
